export const userData = [{
        name: 'Jan',
        'Active User': 4000,
    },
    {
        name: 'Feb',
        'Active User': 3000,
    },
    {
        name: 'Mar',
        'Active User': 2000,
    },
    {
        name: 'Apr',
        'Active User': 2780,
    },
    {
        name: 'May',
        'Active User': 1890,
    },
    {
        name: 'Jun',
        'Active User': 2390,
    },
    {
        name: 'Jul',
        'Active User': 5210,
    },
    {
        name: 'Aug',
        'Active User': 2300,
    },
    {
        name: 'Sep',
        'Active User': 3490,
    },
    {
        name: 'Oct',
        'Active User': 3210,
    },
    {
        name: 'Nov',
        'Active User': 5430,
    },
    {
        name: 'Dec',
        'Active User': 1250,
    },
];

export const productData = [{
        name: 'Jan',
        Sales: 4000,
    },
    {
        name: 'Feb',
        Sales: 3000,
    },
    {
        name: 'Mar',
        Sales: 5000,
    },
    {
        name: 'Apr',
        Sales: 3700,
    },
];

export const userRows = [{
        id: 1,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 2,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 3,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 4,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 5,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 6,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 7,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 8,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 9,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
    {
        id: 10,
        username: 'Jon Snow',
        avatar: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655243233/admin/user_3.jpg',
        email: 'jon@snow.com',
        status: 'active',
        transaction: '$120.00',
    },
];

export const productRows = [{
        id: 1,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 2,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 3,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 4,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 5,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 6,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 7,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 8,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 9,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
    {
        id: 10,
        product: 'Apple Airpods',
        img: 'https://res.cloudinary.com/dhklu5lqa/image/upload/v1655307308/admin/product_1.jpg',
        stock: 123,
        status: 'active',
        price: '$120.00',
    },
];